staging:
    adapter: mysql2
    database: cvp_staging
    username: nebulent
    password: n3bu13NT
    host: 192.168.0.118
    reconnect: true

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
    adapter: mysql2
    database: cvpProduction
    encoding: utf8
    username: root
    password: n3bu13NT
    host: jira.nebulent.com
    port: 3306
    pool: 5
