staging:
    adapter: mysql2
    database: cvp_staging
    username: root
    password: 
    host: 127.0.0.1
    reconnect: true

development:
    adapter: mysql2
    database: cvp_dev
    username: root
    password: 
    host: 127.0.0.1
    reconnect: true

test:
    adapter: mysql2
    database: cvp_test
    username: root
    password:
    host: localhost
    reconnect: true

production:
  adapter: mysql2
  database: cvp_production
  encoding: utf8
  username: cvp_prod
  password: n3bu13nt
  pool: 5
