staging:
    adapter: mysql2
    database: cvp_staging
    username: nebulent
    password: n3bu13NT
    host: 192.168.0.118
    reconnect: true

development:
    adapter: mysql2
    database: cvp_dev
    username: nebulent
    password: n3bu13NT
    host: 192.168.0.118
    reconnect: true

test:
    adapter: mysql2
    database: cvp_test
    username: nebulent
    password: n3bu13NT
    host: 192.168.0.118
    reconnect: true

production:
    adapter: mysql2
    database: cvp_production
    encoding: utf8
    username: nebulent
    password: n3bu13NT
    host: 192.168.0.118
    pool: 5
